export const initialProducts = [
  {
    id: 'khalasi-1l',
    name: 'ხალასი',
    description: 'უნივერსალური საწმენდი და სადეზინფექციო საშუალება ყოველდღიური გამოყენებისთვის.',
    volume: '1 ლ',
    price: 15,
    category: 'უნივერსალური',
    image: '/products/khalasi-1l.webp',
    inStock: true,
    featured: true,
  },
  {
    id: 'khalasi-5l',
    name: 'ხალასი',
    description: 'ეკონომიური მოცულობა სახლისა და პროფესიული დასუფთავებისთვის.',
    volume: '5 ლ',
    price: 40,
    category: 'უნივერსალური',
    image: '/products/khalasi-5l.webp',
    inStock: true,
    featured: false,
  },
  {
    id: 'typhoon-1l',
    name: 'ტაიფუნი',
    description: 'ნადებისა და კირქვის ეფექტური მოსაშორებელი აბაზანისა და სამზარეულოსთვის.',
    volume: '1 ლ',
    price: 15,
    category: 'აბაზანა',
    image: '/products/typhoon-1l.webp',
    inStock: true,
    featured: true,
  },
  {
    id: 'pearl-1l',
    name: 'მარგალიტი',
    description: 'ავეჯისა და მყარი ზედაპირების საპრიალებელი სითხე ბზინვარებისთვის.',
    volume: '1 ლ',
    price: 15,
    category: 'ზედაპირები',
    image: '/products/pearl-1l.webp',
    inStock: true,
    featured: false,
  },
  {
    id: 'laminate-1l',
    name: 'ხისა და ლამინატის საწმენდი',
    description: 'ნაზი ფორმულა ლამინატის, ხისა და შეღებილი ზედაპირების მოსავლელად.',
    volume: '1 ლ',
    price: 15,
    category: 'იატაკი',
    image: '/products/laminate-1l.webp',
    inStock: true,
    featured: false,
  },
  {
    id: 'tskriala-5l',
    name: 'წკრიალა',
    description: 'ჭურჭლის სარეცხი კონცენტრირებული სითხე, რომელიც მარტივად აშორებს ცხიმს.',
    volume: '5 ლ',
    price: 20,
    category: 'სამზარეულო',
    image: '/products/tskriala-5l.webp',
    inStock: true,
    featured: true,
  },
  {
    id: 'family-box',
    name: 'Family Box',
    description: 'საოჯახო ნაკრები ყოველდღიური სისუფთავისთვის — ყველაფერი ერთ ყუთში.',
    volume: 'ნაკრები',
    price: 75,
    category: 'ნაკრებები',
    image: '/products/family-box.webp',
    inStock: true,
    featured: false,
  },
  {
    id: 'mini-box',
    name: 'Mini Box',
    description: 'ოთხი აუცილებელი პროდუქტის კომპაქტური და პრაქტიკული ნაკრები.',
    volume: 'ნაკრები',
    price: 45,
    category: 'ნაკრებები',
    image: '/products/mini-box.webp',
    inStock: true,
    featured: true,
  },
]

export const categories = ['ყველა', 'უნივერსალური', 'სამზარეულო', 'აბაზანა', 'იატაკი', 'ზედაპირები', 'ნაკრებები']

export const demoOrders = [
  { id: '#1048', customer: 'ნინო კ.', total: 55, status: 'ახალი', time: '12:42' },
  { id: '#1047', customer: 'გიორგი მ.', total: 30, status: 'მუშავდება', time: '11:18' },
  { id: '#1046', customer: 'თამარ ბ.', total: 75, status: 'გაგზავნილი', time: 'გუშინ' },
]
